### PR TITLE
feat: add option to exec commands asynchronously

### PR DESCRIPTION
**Pull request by rrkumarshikhar**

### CODE REVIEW

**Comment by rrkumarshikhar** [comment]
[rio.txt](https://github.com/user-attachments/files/17238819/rio.txt) this is the rio binary (added .txt for github upload, remove it while using/testing rio cli)

**Comment by rrkumarshikhar** [comment]
image
image
image
image
image
image

**Comment by rrkumarshikhar** [comment]
this is updated rio-cli for testing purpose:- (Rename the rio.txt to rio) use io-meta pr 1128 for testing.
[rio.txt](https://github.com/user-attachments/files/17301626/rio.txt)

**Review by pallabpain — COMMENTED** [review]
What happens when you don't update set up tools? I understand that it may not work with Python 3.12

File: riocli/device/execute.py [hunk 1]
```diff
@@ -28,15 +28,19 @@
...
 @click.argument('device-name', type=str)
 @click.argument('command', nargs=-1)
 @name_to_guid
 def execute_command(
         device_name: str,
         device_guid: str,
         user: str,
+        timeout: int,
         shell: str,
+        run_async: bool,
```
Comment (ankitrgadiya) [inline riocli/device/execute.py:43]: todo: Please pull from devel and update the docstring to explain the new option.

**Comment by ankitrgadiya** [comment]
I'm getting this error when trying to run the command.
```
<I> rio-async device execute edge01 -- cat /etc/environment --help
Command.__init__() got an unexpected keyword argument 'timeout'
```

File: riocli/device/execute.py (hunk 1 above)
Comment (rrkumarshikhar) [reply riocli/device/execute.py:43]: Done

File: riocli/deployment/execute.py [hunk 2]
```diff
@@ -60,6 +64,10 @@ def execute_command(
     shell is ``/bin/bash``. You can also specify the user using the ``--user``
     option. The default user is ``root``.
 
+    To run the command synchronously,set the --run-async flag to false.
```
Comment (ankitrgadiya) [inline riocli/deployment/execute.py:67]: suggestion: If the default is True, why not call the flag --run-sync and if passed then it would become sync.

File: riocli/device/execute.py [hunk 3]
```diff
@@ -28,23 +28,30 @@
...
```
Comment (ankitrgadiya) [inline riocli/device/execute.py:43]: Same as above

**Review by ankitrgadiya — CHANGES_REQUESTED** [review]

**Review by pallabpain — CHANGES_REQUESTED** [review]
todo: Please rebase with devel and update the dependencies in `pyproject.toml`.

**Review by ankitrgadiya — APPROVED** [review]

File: pyproject.toml [hunk 4]
```diff
@@ -46,7 +46,7 @@ dependencies = [
     "python-magic>=0.4.27",
     "pytz",
     "pyyaml>=5.4.1",
-    "rapyuta-io>=2.0.0",
+    "rapyuta-io @ git+https://git@github.com/rapyuta-robotics/rapyuta-io-sdk.git@feat/device-exec-async",
```
Comment (pallabpain) [inline pyproject.toml:49]: todo: bump SDK version before merging the PR.

**Review by pallabpain — CHANGES_REQUESTED** [review]

**Review by ankitrgadiya — APPROVED** [review]

**Review by pallabpain — APPROVED** [review]
